// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sport.Infrastructure;

#nullable disable

namespace Sport.Infrastructure.Migrations
{
    [DbContext(typeof(SportDbContext))]
    partial class SportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sport.Core.Competitions.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Dates", "Sport.Core.Competitions.Competition.Dates#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("End")
                                .HasColumnType("date")
                                .HasColumnName("dates_end");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date")
                                .HasColumnName("dates_start");
                        });

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_competitions_code");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("Sport.Core.Competitions.CompetitionDiscipline", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<string[]>("EnabledGenders")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("enabled_genders");

                    b.HasKey("Id")
                        .HasName("pk_competition_disciplines");

                    b.HasIndex("CompetitionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_competition_disciplines_competition_id_code");

                    b.ToTable("competition_disciplines", (string)null);
                });

            modelBuilder.Entity("Sport.Core.Officials.OfficialAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FunctionCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("function_code");

                    b.Property<Guid?>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Scope", "Sport.Core.Officials.OfficialAssignment.Scope#OfficialScope", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Level")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("scope_level");

                            b1.Property<Guid>("TargetId")
                                .HasColumnType("uuid")
                                .HasColumnName("scope_target_id");
                        });

                    b.HasKey("Id")
                        .HasName("pk_official_assignments");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_official_assignments_person_id");

                    b.ToTable("official_assignments", (string)null);
                });

            modelBuilder.Entity("Sport.Core.Participants.CompositionMember", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Bib")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bib");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.HasKey("EntryId", "PersonId")
                        .HasName("pk_composition_members");

                    b.HasIndex("PersonId", "EntryId")
                        .IsUnique()
                        .HasDatabaseName("ix_composition_members_person_id_entry_id");

                    b.ToTable("composition_members", (string)null);
                });

            modelBuilder.Entity("Sport.Core.Participants.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bib")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("bib");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer")
                        .HasColumnName("seed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_entries");

                    b.HasIndex("OrganisationId")
                        .HasDatabaseName("ix_entries_organisation_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_entries_team_id");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("ix_entries_event_id_status");

                    b.ToTable("entries", (string)null);
                });

            modelBuilder.Entity("Sport.Core.Participants.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_organisations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_organisations_code");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("Sport.Core.Participants.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("family_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("gender");

                    b.Property<string>("GivenName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("given_name");

                    b.Property<string>("IFId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("if_id");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("FamilyName", "GivenName")
                        .HasDatabaseName("ix_persons_family_name_given_name");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("Sport.Core.Participants.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("DisciplineCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("discipline_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_code");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Sport.Core.Structure.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionDisciplineId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_discipline_id");

                    b.Property<string>("DisciplineCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("discipline_code");

                    b.Property<string>("EventModifier")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("event_modifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("event_type");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Rsc")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("rsc");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("CompetitionDisciplineId", "Rsc")
                        .IsUnique()
                        .HasDatabaseName("ix_events_competition_discipline_id_rsc");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Sport.Core.Structure.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("code");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Rsc")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("rsc");

                    b.HasKey("Id")
                        .HasName("pk_phases");

                    b.HasIndex("EventId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_phases_event_id_code");

                    b.HasIndex("EventId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_phases_event_id_order");

                    b.ToTable("phases", (string)null);
                });

            modelBuilder.Entity("Sport.Core.Structure.Subunit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("code");

                    b.Property<string>("Rsc")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("rsc");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_subunits");

                    b.HasIndex("UnitId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_subunits_unit_id_code");

                    b.ToTable("subunits", (string)null);
                });

            modelBuilder.Entity("Sport.Core.Structure.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<Guid?>("DisciplineUnitRef")
                        .HasColumnType("uuid")
                        .HasColumnName("discipline_unit_ref");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("phase_id");

                    b.Property<string>("Rsc")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("rsc");

                    b.Property<DateTimeOffset?>("ScheduledStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_start");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("PhaseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_units_phase_id_code");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("Sport.Core.Competitions.CompetitionDiscipline", b =>
                {
                    b.HasOne("Sport.Core.Competitions.Competition", null)
                        .WithMany("Disciplines")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competition_disciplines_competitions_competition_id");
                });

            modelBuilder.Entity("Sport.Core.Participants.CompositionMember", b =>
                {
                    b.HasOne("Sport.Core.Participants.Entry", null)
                        .WithMany("Composition")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_composition_members_entries_entry_id");
                });

            modelBuilder.Entity("Sport.Core.Structure.Phase", b =>
                {
                    b.HasOne("Sport.Core.Structure.Event", null)
                        .WithMany("Phases")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_phases_events_event_id");
                });

            modelBuilder.Entity("Sport.Core.Structure.Subunit", b =>
                {
                    b.HasOne("Sport.Core.Structure.Unit", null)
                        .WithMany("Subunits")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subunits_units_unit_id");
                });

            modelBuilder.Entity("Sport.Core.Structure.Unit", b =>
                {
                    b.HasOne("Sport.Core.Structure.Phase", null)
                        .WithMany("Units")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_units_phases_phase_id");
                });

            modelBuilder.Entity("Sport.Core.Competitions.Competition", b =>
                {
                    b.Navigation("Disciplines");
                });

            modelBuilder.Entity("Sport.Core.Participants.Entry", b =>
                {
                    b.Navigation("Composition");
                });

            modelBuilder.Entity("Sport.Core.Structure.Event", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("Sport.Core.Structure.Phase", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("Sport.Core.Structure.Unit", b =>
                {
                    b.Navigation("Subunits");
                });
#pragma warning restore 612, 618
        }
    }
}
